Run the fat jar instead of using "sbt run"

diff --git a/ansible/run-scalex b/ansible/run-scalex
--- a/ansible/run-scalex
+++ b/ansible/run-scalex
@@ -1,6 +1,11 @@
 #! /bin/bash
-kill $(ps ax | grep /usr/bin/sbt | awk '{ print $1 }')
-sleep 5
+set -e
 
-cd ~/scalex
-nohup /usr/bin/sbt 'run --listen 8000' &
+PIDFILE=$HOME/scalex.pid
+
+if [ -e $PIDFILE ]; then
+    kill $(cat $PIDFILE) || echo "Failed to kill"
+fi
+
+nohup java -Dscala.usejavacp=true -jar scalex-assembly-3.0-SNAPSHOT.jar --listen 8000 &
+echo $! > $PIDFILE
